python95/post/urls.py
from . import views
from django.urls import path
from post.views import PostDeleteView

app_name = 'post'

urlpatterns = [
    path("posts/", views.posts, name="posts"),
    path('posts/<int:post_id>/', views.posts_view, name="posts"),
    path("create/", views.create, name="create"),
    path("edit/<int:post_id>/", views.edit_post, name="edit_post"),
    path("<int:pk>/delete", PostDeleteView.as_view(), name="post_delete"),
    path('subject<int:subject_id>/', views.posts, name='subject'),
    path('post_comment/<int:post_id>/', views.post_comment, name='post_comment'),
]

python95/python95_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls")),
    path("", include("post.urls")),
    path("",include("announcement.urls")),


]

if settings.DEBUG:
  urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

python95/post/models.py
from django.db import models
from announcement.models import Subject
from user.models import NewUser


class Post(models.Model):
    CHOICES = (
        ('+', "+"),
        ("-", "-")
    )
    TIME = (
        ('30', "30"),
        ("45", "45"),
        ("60", "60"),
        ("90", "90"),
    )
    CURRENCY = (
        ("USD", "USD"),
        ("BYN", "BYN"),
        ("RUB", "RUB"),
    )

    image = models.ImageField(null=False, blank=False, upload_to="images")
    first_name = models.CharField(max_length=100, null=False, blank=False)
    second_name = models.CharField(max_length=100, null=False, blank=False)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    about = models.TextField(max_length=500, blank=True, null=True)
    qualification = models.CharField(max_length=200, null=False, blank=False)
    work_experience = models.CharField(max_length=300, null=False, blank=False, )
    organizations = models.CharField(max_length=300, null=False, blank=False)
    address = models.CharField(max_length=100, null=False, blank=False, )
    online_lessons = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    offline_lessons = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    lessons_at_home = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    price = models.PositiveIntegerField(null=False, blank=False)
    time_of_lesson = models.CharField(choices=TIME, default="60", null=False, blank=False, max_length=100)
    add_information = models.CharField(max_length=100, null=True, blank=True)
    currency = models.CharField(max_length=100, choices=CURRENCY, default="BYN", null=False, blank=False)
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, null=False, blank=False)

    def __str__(self):
        return self.second_name


class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.Model,related_name='comments')
    name=models.ForeignKey(NewUser,on_delete=models.CASCADE,related_name='name')

    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    active=models.BooleanField(default=False)

    class Meta:
        ordering=['created']
        indexes=[models.Index(fields=['created'])]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

python95/post/forms.py
from django import forms
from post.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("image", "first_name", "second_name",
                  "subject",
                  "about",
                  "qualification",
                  "work_experience",
                  "organizations",
                  "address",
                  "online_lessons",
                  "offline_lessons",
                  "lessons_at_home",
                  "price",
                  "currency",
                  "time_of_lesson",
                  "add_information",
                  'phone_number',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

python95/post/views.py
from django.contrib.auth.decorators import permission_required, login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from post.forms import PostForm
from post.models import Post
from announcement.models import Subject
from post.forms import CommentForm
from post.models import Comment


@login_required
def posts(request, subject_id=None):
    if subject_id:
        post = Post.objects.filter(subject_id=subject_id)
    else:
        post = Post.objects.all()
    paginator = Paginator(post, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'subjects': Subject.objects.all(),
        'posts': posts,

    }
    return render(request, "posts.html", context)


@login_required
def posts_view(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.all()
    form = CommentForm()
    return render(request, "posts_view.html", {"post": post, 'comments': comments, 'form': form})


@permission_required(perm="post.add_post", raise_exception=True)
def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            form.save_m2m()
            return redirect("post:posts")
        else:
            return redirect("post:posts")
    else:
        form = PostForm()
    return render(request, "create.html", {"form": form})


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.user:
        return redirect(f"/posts/{post_id}/")
    if request.method == "GET":
        form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
        return redirect("post:posts")
    return render(request, "edit_post.html", {"form": form, "post": post})


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("post:posts")
    template_name = "delete_post.html"


def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user
        comment.save()
    return render(request, 'post_comment.html', {'post': post, 'form': form, 'comment': comment})

python95/post/templates/comment_form.html
<h2>Add a new comments</h2>
<form  method="post" action="{% url 'post:post_comment' post.id%}  ">
    {{ form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Add comment"></p>
</form>

python95/post/templates/create.html
{% extends "base.html" %}
{% block content %}
<link rel="shortcut icon" href="#" />
<div class="container">
     <h2>Create Post</h2>
<form method="post" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <link rel="icon" href="media/images/favicon.ico">
    <button type="subbmit" class="save bth-default">Save</button>
</form>
</div>
{% endblock %}

python95/post/templates/delete_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h2>Are you sure you want to delete this post ?</h2>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-success" type="submit">Delete</button>
</form>
</div>

{% endblock %}

python95/post/templates/edit_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
     <h2>Edit Post</h2>
<form method="post" class="post-form" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="subbmit" class="save bth-default">Save</button>
    <a href="{% url "post:post_delete" post.id%}">Delete</a>
</form>
</div>
{% endblock %}

python95/post/templates/pagination.html
<div class="pagination"> <span class="step-links">
    <div class="container">
{% if page.has_previous %}
<a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
{% if page.has_next %}
<a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}
    </div>
</span> </div>

python95/post/templates/post_comment.html
{% extends "base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %} {% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{%  url 'post:posts' post_id=post.id %}">Back to the post</a></p> {% else %}
{% include "comment_form.html" %}
    {%  endif %}
{%  endblock %}

python95/post/templates/posts.html
{% extends "base.html" %}
{% block content %}

<div class="container" >
    {% if perms.post.add_post %}
         <button type="submit" class="nav-link btn btn-link"></button>
        <style="display: inline; border: none; background: none; box-shadow: none;" ><a  style="color:black"  href="{% url 'post:create' %}">Add post</a></style></button>
         <link rel="shortcut icon" href="#" />
          {% endif %}
<br>
<style>
    div.flex{
    display:flex;
    text-align:left;
        border-spacing: 1000px;
    }
</style>
    <div class="flex">
    <p>filter:</p>
     {%  for subject in subjects %}
         <a href="{%  url 'post:subject' subject.id %}" style="color:black"> {{ subject.subject }} </a>
{%  endfor%}
    </div>
</div>
{% for post in posts %}
    <div class="container">
    <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
                <img class="img-article-left" src="{{post.image.url}}" width="370px"  height=350" align="left" />
              <h1 class="card-text">{{post.first_name}} {{post.second_name}}</h1>
                <h3>Subject: {{post.subject}}</h3>
                <h3>qualification: {{post.qualification}}</h3>
                <h3>Address: {{post.address}}</h3>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url "post:posts" post_id=post.id %}" style="color:black">View</a></button>
              </div>
              </div>
            </div>
              </div>
            </div>
          </div>
        </div>
    {%  empty %}


{% endfor %}
<div class ="container">{% include "pagination.html" with page=posts %}</div>
{% endblock %}

python95/post/templates/posts_view.html
{% extends "base.html" %}

{% block content %}

<div class="container">
<div  class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <h1 style="color: black">{{post.first_name}} {{post.second_name}}</h1>
            <p style="color: black" ><img src="{{post.image.url}}"align="left" width="650",height="720" />
            <br>

            Subject:{{post.subject}}
                <br>
            Information about:{{post.about}}
                <br>
             Qualifications:{{post.qualification}}
                <br>
                Work experience:{{post.work_experience}} at {{post.organizations}}
                <br>
                Teachers address: {{post.address}}
                <br>
                Online lessons: {{post.online_lessons}}
                <br>
                Offline lessons : {{post.offline_lessons}}
                <br>
                Lessons at teachers place:{{post.lessons_at_home}}
                <br>
                Price:{{post.price}}{{post.currency}} for {{post.time_of_lesson}}minutes
                <br>
                Additional information:{{post.add_information}}
            </p>
            {% if post.user == request.user %}
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url "post:edit_post" post_id=post.id %}" style="color:black">Edit</a></button>
                    {% endif %}

{%  with comments.count as total_comments %}
        <h2>
            {{total_comments}} comment{{ total_comments|pluralize }}

        </h2>
        {%  endwith %}
        {%  for comment in comments  %}
        <div class="comment">
            <p class="info">
            <h3><i class="bi bi-chat-right-text"></i>Comment{{forloop.counter }} by {{ comment.name }}</h3>
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {%  empty %}
        <p>There are no comments </p>
        {%  endfor %}
        {%  include 'comment_form.html' %}


    </div>
</div>

{% endblock %}