python95/announcement/urls.py
from django.urls import path, include
from . import views
from .views import AnnouncementDeleteView

app_name = 'announcement'

urlpatterns = [
    path("create_announcement/", views.add_announcement, name="create_announcement"),
    path("announcements/", views.announcement, name="announcements"),
    path("edit_announcement/<int:announcement_id>/", views.edit_announcement, name="edit_announcement"),
    path('announcement/<int:announcement_id>/', views.announcement_detail, name='announcement'),
    path("<int:pk>/delete/", AnnouncementDeleteView.as_view(), name="delete_announcement"),
    path("<int:subject_id>/", views.announcement, name='subject'),

]

python95/post/urls.py
from . import views
from django.urls import path
from post.views import PostDeleteView

app_name = 'post'

urlpatterns = [
    path("posts/", views.posts, name="posts"),
    path('posts/<int:post_id>/', views.posts_view, name="posts"),
    path("create/", views.create, name="create"),
    path("edit/<int:post_id>/", views.edit_post, name="edit_post"),
    path("<int:pk>/delete", PostDeleteView.as_view(), name="post_delete"),
    path('subject<int:subject_id>/', views.posts, name='subject'),
    path('post_comment/<int:post_id>/', views.post_comment, name='post_comment'),
]

python95/python95_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls")),
    path("", include("post.urls")),
    path("",include("announcement.urls")),


]

if settings.DEBUG:
  urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

python95/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.login_request, name='login'),
    path('account/',views.account,name='account'),
    path('logout/',views.custom_logout,name='logout')
]

python95/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class NewUser(AbstractUser):
    ROLE = (
        ('student', "student"),
        ('teacher', "teacher"),
    )
    username = models.CharField(max_length=100, null=False, blank=False, unique=True)
    email = models.EmailField(unique=True, max_length=110, null=False, blank=False)
    password = models.CharField(max_length=100, null=False, blank=False)
    role = models.CharField(choices=ROLE, default="student", max_length=20)

    def __str__(self):
        return self.email


from django.db import models

# Create your models here.

python95/user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.http import HttpResponse
from user.models import NewUser


class UserRegisterForm(forms.ModelForm):
    groups = forms.ModelChoiceField(queryset=Group.objects.all())
    username = forms.CharField(label='username')
    email = forms.CharField(label='email')
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', "email", "password", "groups"]

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            return HttpResponse('This email is already exists')
        return email

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

python95/user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from user.models import NewUser
from user.forms import UserRegisterForm
from announcement.models import Announcement
from post.models import Post


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            email = request.POST.get('email')
            user_group = Group.objects.get(name=form.cleaned_data['groups'])
            user.groups.add(user_group)
            send_mail(
                'Welcome',
                f'Nice to meet you {user}!',
                'EMAIL_HOST_USER',
                [email],
                fail_silently=False
            )
            return redirect("login")
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {"form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"hellow{username}")
                return redirect('post:posts')
            else:
                messages.info(request, "Username or password is not  correct ")
        else:
            messages.info(request, "Username or password is not  correct ")
    form = AuthenticationForm()
    return render(request, 'login.html', {"form": form})


def custom_logout(request):
    logout(request)
    return redirect("login")


def account(request):
    context = {
        "announcement": Announcement.objects.filter(user=request.user),
        "posts": Post.objects.filter(user=request.user),
        "users": NewUser.objects.filter(email=request.user)
    }
    return render(request, 'account.html', context)

python95/user/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1 align="center">Personal account</h1>
        {% for user in users %}
        <h3>Username:{{user.username}}</h3>
        <h3>Email:{{user.email}}</h3>
        {% endfor %}
        {% for ann in announcement %}
        <div class="card shadow-sm">
        <h1>{{ann.first_name}}</h1>
                <h3>Grade: {{ann.form}}</h3>
                <h3>City: {{ann.city}}</h3>
                <h3>Price:{{ann.price_limit_from}}-{{ann.price_limit_to}}</h3>
                <h3>Level: {{ann.level_of_knowledge}}</h3>
        {% endfor %}
        {%for post in posts %}
                                 <h1 align="left" >My Posts:</h1>
                            <div class="card shadow-sm">
               <img class="img-article-left" src="{{post.image.url}}" width="300px"  height=320" align="left" />
              <h1 class="card-text">{{post.first_name}} {{post.second_name}}</h1>
                <h3>Subject: {{post.subject}}</h3>
                <h3>qualification: {{post.qualification}}</h3>
                <h3>Address: {{post.address}}</h3>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url "post:posts" post_id=post.id %}" style="color:black">View</a></button>
              </div>

        </div>
        {% endfor %}

        </form>
    </div>
{% endblock %}

python95/user/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <div class="container">
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          {% if user.is_authenticated %}
           <button type="submit" class="nav-link btn btn-link">
                 <style="display: inline; border: none; background: none; box-shadow: none;" ><a  style="color:black"  href="{% url 'post:posts' %}">Teachers posts</a></button>
         <button type="submit" class="nav-link btn btn-link">
             <style="display: inline; border: none; background: none; box-shadow: none;" ><a  style="color:black"  href="{% url 'announcement:announcements' %}">Students anouncement</a></button>
        <button type="submit" class="nav-link btn btn-link">
                 <style="display: inline; border: none; background: none; box-shadow: none;" ><a  style="color:black"  href="{% url 'account' %}"> Account</a></button>
         <link rel="shortcut icon" href="#" />
        {% endif %}
    <div class="col-4 text-center">
          <h3 align="center"><a class="blog-header-logo text-body-emphasis text-decoration-none"  style="color:black"  >Pro study </a></h3>
      </div>
        <div class="text-right">
          {% if request.user.is_authenticated  %}
            <form action="{% url 'logout' %}" method="post" class="form-inline">
                {% csrf_token %}
                <button type="submit" class="nav-link btn btn-link" style="color:black"
                        style="display: inline; border: none; background: none; box-shadow: none;">LogOut
                </button>
            </form>
            {% else %}
      <ul class="nav">
        <li class="nav-item"><a  href="{% url "register" %}"  class="btn btn-sm btn-outline-secondary"  style="color:black"
            class="nav-link link-body-emphasis px-2">SignUp</a></li>
        <li class="nav-item"><a class="btn btn-sm btn-outline-secondary"  href="{% url "login" %}" style="color:black" class="nav-link link-body-emphasis px-2">LogIn</a></li>
      </ul>
          {% endif %}
        </div>
      </div>
      <header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
      <div class="col-4 d-flex justify-content-end align-items-center">
            <style>
                body {
                    background: #fdf5d7;
                    color: #000000;
                    font-family: "Times New Roman";
                }
            </style>

      </div>
    </div>
  </header>
    </div>
</head>
<body bgcolor="blue">
{% block content %}
{% endblock %}
</body>
</html>

python95/user/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Log IN</h1>
        <form method="post" >
            {% csrf_token %}
        {{ form.as_p }}

        <p><button type="submit">Enter</button></p>
        </form>
    </div>
{% endblock %}

python95/user/templates/logout.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to logout?</p>
            <button type="submit">Yes,logout</button>
        </form>
    </div>

{% endblock %}

python95/user/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Registrations</h1>
        <form method="post" >
            {% csrf_token %}
        {{ form.as_p }}
        <p><button type="submit">Enter</button></p>
        </form>
    </div>
{% endblock %}