python95/announcement/urls.py
from django.urls import path, include
from . import views
from .views import AnnouncementDeleteView

app_name = 'announcement'

urlpatterns = [
    path("create_announcement/", views.add_announcement, name="create_announcement"),
    path("announcements/", views.announcement, name="announcements"),
    path("edit_announcement/<int:announcement_id>/", views.edit_announcement, name="edit_announcement"),
    path('announcement/<int:announcement_id>/', views.announcement_detail, name='announcement'),
    path("<int:pk>/delete/", AnnouncementDeleteView.as_view(), name="delete_announcement"),
    path("<int:subject_id>/", views.announcement, name='subject'),

]

python95/post/urls.py
from . import views
from django.urls import path
from post.views import PostDeleteView

app_name = 'post'

urlpatterns = [
    path("posts/", views.posts, name="posts"),
    path('posts/<int:post_id>/', views.posts_view, name="posts"),
    path("create/", views.create, name="create"),
    path("edit/<int:post_id>/", views.edit_post, name="edit_post"),
    path("<int:pk>/delete", PostDeleteView.as_view(), name="post_delete"),
    path('subject<int:subject_id>/', views.posts, name='subject'),
    path('post_comment/<int:post_id>/', views.post_comment, name='post_comment'),
]

python95/python95_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls")),
    path("", include("post.urls")),
    path("",include("announcement.urls")),


]

if settings.DEBUG:
  urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

python95/announcement/models.py
from django.db import models
from user.models import NewUser


class Subject(models.Model):
    subject = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.subject


class Announcement(models.Model):
    CHOICES = (
        ('+', "+"),
        ("-", "-")
    )
    LEVELS = (
        ('Elementary(A1)', "Elementary(A1"),
        ("Pre-Intermediate(A2)", "Pre-Intermediate(A2"),
        ("Intermediate(B1)", "Intermediate(B1)"),
        ('Upper-Intermediate(B2)', 'Upper-Intermediate(B2)'),
        ('Advanced(C1,C2)', 'Advanced(C2)'),
    )
    CURRENCY = (
        ("USD", "USD"),
        ("BYN", "BYN"),
        ("RUB", "RUB"),
    )
    first_name = models.CharField(max_length=50, null=False, blank=False)
    form = models.IntegerField(null=True, blank=True)
    age = models.IntegerField(null=False, blank=False)
    city = models.CharField(max_length=50, null=False, blank=False)
    address = models.CharField(max_length=150, null=False, blank=False)
    price_limit_from = models.IntegerField(null=False, blank=False)
    price_limit_to = models.IntegerField(null=False, blank=False)
    online_lessons = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    offline_lessons = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    lessons_at_home = models.CharField(max_length=100, choices=CHOICES, default="+", null=False, blank=False)
    level_of_knowledge = models.CharField(max_length=100, choices=LEVELS, default="+", null=False, blank=False)
    phone_number = models.CharField(null=True, blank=True)
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    currency = models.CharField(max_length=100, choices=CURRENCY, default="BYN", null=False, blank=False)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

python95/announcement/forms.py
from django import forms

from announcement.models import Announcement


class StudentAnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ("first_name", "form", "age", "city", "address", "price_limit_from", "price_limit_to", "currency",
                  "online_lessons",
                  "offline_lessons",
                  "lessons_at_home", "level_of_knowledge", "phone_number", "subject")

python95/announcement/views.py
from django.contrib.auth.decorators import permission_required, login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from announcement.models import Announcement
from announcement.forms import StudentAnnouncementForm
from announcement.models import Subject


@login_required()
def announcement(request, subject_id=None):
    if subject_id:
        announcement = Announcement.objects.filter(subject_id=subject_id)
    else:
        announcement = Announcement.objects.all()
    paginator = Paginator(announcement, 2)
    number = request.GET.get('page', 1)
    try:
        announcements = paginator.page(number)
    except PageNotAnInteger:
        announcements = paginator.page(1)
    except EmptyPage:
        announcements = paginator.page(paginator.num_pages)
    context = {
        'subject': Subject.objects.all(),
        'announcements': announcements,

    }
    return render(request, "announcement.html", context)


@login_required()
def announcement_detail(request, announcement_id):
    announcement = get_object_or_404(Announcement, id=announcement_id)
    return render(request, 'announcement_view.html', {'announcement': announcement})


@permission_required(perm="announcement.add_announcement", raise_exception=True)
def add_announcement(request):
    if request.method == "POST":
        form = StudentAnnouncementForm(request.POST, request.FILES)
        if form.is_valid():
            ann = form.save(commit=False)
            ann.user = request.user
            ann.save()
            form.save_m2m()
            return redirect("announcement:announcements")
        else:
            return redirect("announcement:announcements")
    else:
        form = StudentAnnouncementForm()
    return render(request, "add_announcement.html", {"form": form})


@login_required()
def edit_announcement(request, announcement_id):
    announcement = get_object_or_404(Announcement, id=announcement_id)
    if request.user != announcement.user:
        return redirect(f"/announcements/{announcement_id}/")
    if request.method == "GET":
        form = StudentAnnouncementForm(instance=announcement)
    if request.method == 'POST':
        form = StudentAnnouncementForm(request.POST, instance=announcement)
        if form.is_valid():
            form.save()
        return redirect("announcement:announcements")
    return render(request, "edit_announcement.html", {"form": form, "announcement": announcement})


class AnnouncementDeleteView(DeleteView):
    model = Announcement
    success_url = reverse_lazy("announcement:announcements")
    template_name = "delete_announcement.html"

python95/announcement/templates/add_announcement.html
{% extends "base.html" %}
{% block content %}
<link rel="shortcut icon" href="#" />
<div class="container">
     <h2>announcement</h2>
<form method="post" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <link rel="icon" href="media/images/favicon.ico">
    <button type="subbmit" class="save bth-default">Save</button>
</form>
</div>
{% endblock %}

python95/announcement/templates/announcement.html
{% extends "base.html" %}
{% block content %}
<div class="container" >
          {% if perms.announcement.add_announcement %}
         <button type="submit" class="nav-link btn btn-link"></button>
              <style="display: inline; border: none; background: none; box-shadow: none;" ><a  style="color:black"  href="{% url 'announcement:create_announcement' %}">Add announcement</a></button>
         <link rel="shortcut icon" href="#" />
          {% endif %}
    <br>
     {%  for subject in subject %}
         <a href="{%  url 'announcement:subject' subject.id %}" style="color:black"> {{ subject.subject }} </a>
{%  endfor%}
    </div>
    <div class="col">
        {% for announcement in announcements %}
            <div class="container">
          <div class="card shadow-sm">
            <div class="card-body">
              <h1 class="card-text">{{announcement.first_name}}</h1>
                <h3>Grade: {{announcement.form}}</h3>
                <h3>Subject: {{announcement.subject}}</h3>
                <h3>Price:{{announcement.price_limit_from}}-{{announcement.price_limit_to}}{{ announcement.currency }}</h3>
                <h3>Level: {{announcement.level_of_knowledge}}</h3>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group"></div>
              </div>
                <a href="{% url 'announcement:announcement' announcement_id=announcement.id %}">View</a>

              </div>
              </div>
            </div>
{% endfor %}
<div class ="container">{% include "pagination.html" with page=announcements %}</div>
{% endblock %}

python95/announcement/templates/announcement_view.html
{% extends "base.html" %}

{% block content %}

<div class="container">
<div  class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <h3 style="color: black">Name:{{announcement.first_name}} </h3>
            <h3 style="color: black">Form:{{announcement.form}} </h3>
            <h3 style="color: black">Age:{{announcement.age}} </h3>
            <h3 style="color: black">City:{{announcement.city}} </h3>
            <h3 style="color: black">Addres:{{announcement.address}} </h3>
            <h3 style="color: black">Price:{{announcement.price_limit_from}} - {{announcement.price_limit_to}}{{announcement.currency}}</h3>
            <h3 style="color: black">Online lessons:{{announcement.online_lessons}} </h3>
            <h3 style="color: black">Offline lessons:{{announcement.offline_lessons}} </h3>
            <h3 style="color: black">Lessons at home :{{announcement.lessons_at_home}} </h3>
            <h3 style="color: black">Level of knowledge:{{announcement.level_of_knowledge}} </h3>
            <h3 style="color: black">Phone number:{{announcement.phone_number}} </h3>
            <h3 style="color: black">Subject:{{announcement.subject}} </h3>
        </div>
        {% if  announcement.user == request.user %}
    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url "announcement:edit_announcement" announcement_id=announcement.id %}">Edit</a></button>
    {% endif %}
    </div>
</div>

{% endblock %}

python95/announcement/templates/delete_announcement.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h2>Are you sure you want to delete this announcement ?</h2>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-success" type="submit">Delete</button>
     <a  href="{% url "announcement:announcements" %}">Back</a>
</form>
</div>

{% endblock %}

python95/announcement/templates/edit_announcement.html
{% extends "base.html" %}
{% block content %}
<div class="container">
     <h2>Edit Announcement</h2>
<form method="post" class="post-form" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="subbmit" class="save bth-default">Save</button>
    <a href="{% url "announcement:delete_announcement" announcement.id %}">Delete</a>

</form>
</div>
{% endblock %}